services:
  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
